### ISSUE TITLE
Feature Request  - Language Bridge / Multilanguage Support

### ISSUE THREAD

**Issue by ShadetHeart** [Kagurame/FXSpindle#6]
Is it possible to add some kind of multilanguage support? - So if I write something in lua, and would like to use a function I already wrote some other day in Ruby - can I use them both in one script?

**Comment by Kagurame** [comment]
Currently it seems impossible since ruby cant instanciate when its called as subprocess of IDE (FXSpindle).

Were looking ahead to fix this, but its unclear currently...
