### ISSUE TITLE
Feature Request - Edit ass in IDE

### ISSUE THREAD

**Issue by ShadetHeart** [Kagurame/FXSpindle#8]
I would love being able to edit the .ass file inside of the program.

**Comment by ShadetHeart** [comment]
For being able to make a fast timing fix or a little rephrase without using multiple programs :)

**Comment by Kagurame** [comment]
If I would implement this, then i had to implement a complete KTime tool in this software. Thats not for what it is.
FXSpindle solves the problem, that you have to use a bunch of programms, b ut its not concipated as standalone application.
